spring:
  rsocket:
    server:
      port: ${RSOCKET_PORT:7070}

mqtt:
  host: ${MQTT_HOST:localhost}
  port: ${MQTT_PORT:1883}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  qos: ${MQTT_QOS:2}
  reconnection-delay: ${MQTT_RECONNECTION_DELAY:128000}
  topic-base-path: ${MQTT_TOPIC_BASE_PATH:}
  enable-topic-unique-ids: ${MQTT_UNIQUE_TOPICS_ENABLED:false}

internal:
  subscriber:
    retry-attempts: 2
    retry-delay-millis: 1000

logging:
  level:
    com.github.ngnhub.iot_device_simulator: ${LOG_LEVEL:info}

description:
  default-resource: 'default_sensors.json'
