spring:
  rsocket:
    server:
      port: 7070

#todo all props from variable

mqtt:
  host: 'localhost'
  port: 1883
  username: 'admin'
  password: 'admin'

internal:
  subscriber:
    retry-attempts: 2
    retry-delay-millis: 1000

logging:
  level:
    com.github.ngnhub.iot_device_simulator: debug

description:
  default-resource: 'default_sensors.json'
